/*
 Copyright 2014 John Duane. All rights reserved.
 Use of this source code is governed by a BSD-style license that can be
 found in the LICENSE file.

 The following code processes a file type of "cpuprofile" generated by Chrome's developer tools.
 The intent is to expose a simplified version of the file that rolls up all unique combination of url and function
 into a single object that contains the time spent in that function.

 The code takes as input the path to a cpuprofile file and generates a 'profileHash' object containing:
 - Object hash key of url|function
 - url: string; typically to a JavaScript file
 - function: string; typically a minified function name
 - time: number; the total cpu time spent in the function

 */

module.exports = Har;

var fs = require('fs');

function Har(filePath) {
    var file = fs.readFileSync(filePath);
    if (!file) {
        file = fs.readFileSync(path.join(__dirname, filePath));
    }
    if (!file) {
        file = fs.readFileSync(path.join(process.cwd(), filePath));
    }
    if (!file) throw ({message:"Can't process har file: " + filePath});

    var har = JSON.parse(file);

    if (har && har.log && har.log.entries) {
        this.harJs = {fileProcessed: filePath, pages: har.log.pages};
        this._processEntries(har.log.entries);
    }
    else {
        this.harJs = null;
        throw({message:"Can't process har file: " + filePath});
    }
}

Har.prototype = {

    generateDetails: function() {
        var tsv = "HAR file: " + this.harJs.fileProcessed + "\n" +
                  "Page\tURL\tTotal Request Time\n";
        for(var i = 0; i < this.harJs.entries.length; i++) {
            tsv +=
                this.harJs.entries[i].page + "\t" +
                this.harJs.entries[i].url + "\t" +
                this.harJs.entries[i].time + '\n';
            //TODO: write other timings
        }
        return tsv;
    },

    generateSummary: function() {
        var i, j, totalTime, totalJsFiles;
        var tsv = "HAR file: " + this.harJs.fileProcessed + "\n" +
                  "Page\tCount of .js files\tTotal Request Time\n";
        for (i = 0; i < this.harJs.pages.length; i++) {
            totalTime = totalJsFiles = 0;
            for (j = 0; j < this.harJs.entries.length; j++) {
                if (this.harJs.pages[i].title === this.harJs.entries[j].page) {
                    totalJsFiles++;
                    totalTime += this.harJs.entries[j].time;
                }
            }
            tsv +=
                this.harJs.pages[i].title + "\t" +
                totalJsFiles + "\t" +
                totalTime + "\n";

        }
        return tsv;
    },

    _processEntries: function(entries) {
        var i;
        if (Array.isArray(entries)) {
            this.harJs.entries = [];
            for (i = 0; i < entries.length; i++) {
                if (isEntryJavaScript(entries[i].response.headers)) {
                    this.harJs.entries.push({
                        page: getEntryPage(this.harJs.pages, entries[i].pageref),
                        url: entries[i].request.url,
                        time: entries[i].time
                        //TODO: get other timings
                    });
                }
            }
        }

        function isEntryJavaScript(headers) {
            var i, found = false;
            for (i = 0; i < headers.length && !found; i++) {
                if (headers[i].value.indexOf('javascript') !== -1 )
                    found = true;
            }
            return found;
        }

        function getEntryPage(pages, pageRef) {
            var i, foundPage = null;
            for (i = 0; i < pages.length && !foundPage; i++) {
                if (pages[i].id === pageRef)
                    foundPage = pages[i].title;
            }
            return foundPage;
        }
    }

};
